/**
 * @file print_hello_world.js
 * @author graeme@converse.ai
 * @description This module will print "Hello World" to the conversation.
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.ModuleResponse;

module.exports = function print_hello_world (app, body) {
 /**
  * Registration parameters assigned to body.payload.registrationData
  * and Module parameters assigned to body.payload.moduleParam.
  * @example
  * var regOne = body.payload.registrationData.regOne;
  * var modOne = body.payload.moduleParam.modOne;
  */

  /** @type {ModuleResponse} response The Converse AI response to respond with. */
  var response = new ModuleResponse();

  /*
  * Set an array of comments on the response. Each comment will result in a
  * separate reply on the current conversation by the system.
  */
  response.setComment(['Hello, World!']);

  /*
  * This will return a success status and response to the conversation.
  * It is important to always call this method when the module has finished
  * computing regardless of whether you wish to send a response or not. If not,
  * the conversation will hang indefinitely.
  */
  app.send(Status.SUCCESS, response);
};
